// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODCC.Infrastructure.Modules.Analytics.Persistence;

#nullable disable

namespace ODCC.Infrastructure.Modules.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ODCC.Domain.Modules.Analytics.Entities.Benchmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompanyWide")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgUnitPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Metric", "IsCompanyWide", "OrgUnitId");

                    b.ToTable("benchmarks", (string)null);
                });

            modelBuilder.Entity("ODCC.Domain.Modules.Analytics.Entities.SurveyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CampaignCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CesQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CesRespondents")
                        .HasColumnType("int");

                    b.Property<decimal?>("CesScore")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CompletedSessions")
                        .HasColumnType("int");

                    b.Property<decimal>("CompletionRate")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CsatQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CsatRespondents")
                        .HasColumnType("int");

                    b.Property<decimal?>("CsatScore")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NpsDetractors")
                        .HasColumnType("int");

                    b.Property<int>("NpsPassives")
                        .HasColumnType("int");

                    b.Property<int>("NpsPromoters")
                        .HasColumnType("int");

                    b.Property<Guid?>("NpsQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NpsScore")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgUnitPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("QuestionMetrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingRespondents")
                        .HasColumnType("int");

                    b.Property<int>("RespondedDistributions")
                        .HasColumnType("int");

                    b.Property<decimal?>("ResponseRate")
                        .HasColumnType("decimal(18,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SegmentType")
                        .HasColumnType("int");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SurveyCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SurveyTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TotalDistributions")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SegmentType");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "SegmentType", "OrgUnitId", "CampaignId", "Source")
                        .IsUnique()
                        .HasFilter("[OrgUnitId] IS NOT NULL AND [CampaignId] IS NOT NULL AND [Source] IS NOT NULL");

                    b.ToTable("survey_metrics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
